### ISSUE TITLE
EVM security bugs

### ISSUE THREAD

**Issue by guidovranken** [neonevm/neon-evm#901]
On June 29th 2023 I sent an email about this matter to info@neon-labs.org but received no response. Please respond if you want to receive reports about EVM bugs.

**Comment by gigimon** [comment]
Hello, sorry for delay. Do You still have security reports?

**Comment by guidovranken** [comment]
Yes I do. Can you e-mail me at guido@guidovranken.com ?

**Comment by gigimon** [comment]
done :)
