### ISSUE TITLE
trustless bridges support: split out EVM test run to make a IBC bridge on top of NEON EVM 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [neonevm/neon-evm#911]
```
The proxy will take the Neon transaction and perform a "test run" using its internal EVM emulator. The "test run" will identify the list of accounts accessed by the transaction along with the following attributes of each account:

Flag indicating whether it's an existing account or a new account created as part of the transaction
Flag indicating whether the transaction will read or write to the account
```

so as part of IBC packet transfer we need to access arbitrary accounts.
 
for that IBC relayer need to know arbitrary accounts.

so need to call into test run with IBC packets

**Comment by dzmitry-lahoda** [comment]
how much time it will take?

**Comment by dzmitry-lahoda** [comment]
what source code to look at exactly?

**Comment by dzmitry-lahoda** [comment]
# Value

Everybody happy - we all get IBC Trustless bridge from Cosmos <-> Solana

**Comment by afalaleev** [comment]
This already works.
You can try Neon EVM endpoints https://chainlist.org/?search=Neon+EVM, which provide Ethereum-like RPC.
You can communicate with Neon with standard Ethereum-like frameworks.
